### ISSUE TITLE
GogoWatch project endorsement

### ISSUE THREAD

**Issue by Gogo1951** [valkyrnstudios/SpellSentinel#5]
Hey @SabreValkyrn ,

Nice work on this!

Only request... if you use any project with an MIT License, it's important to keep the same MIT License.

Long chat on that here.

https://github.com/Gogo1951/GogoWatch/commit/686aa1c68493654616a69c374aa04d1dadf3258b#comments

Feel free to take any idea around features I had posted and run with them. https://github.com/Gogo1951/GogoWatch/projects/1

Glad someone is making this work!

Oh, and I'd love to see it work for SoM too if you get a chance. (=

**Comment by Gogo1951** [comment]
Not to air too much dirty laundry, but I didn't know I could get kicked off my own Discord.

Here's the post I made there before Tex deleted it.

-- 

Hey everyone, I don't really want to be involved with this any more...

Just wanted to say that I am happy to have anyone take anything I've done and run with it.

I hated that this project stagnated.

Few points...

1 - I'm not a fan of Overwolf. Changing the license to promote Overwolf was not something I was across.

* Update LICENSE · Gogo1951/GogoWatch@686aa1c | <https://github.com/Gogo1951/GogoWatch/commit/686aa1c68493654616a69c374aa04d1dadf3258b#comments>

2 - I think open-source is great, and anyone who wants to run with this has my blessing. It wasn't my idea, just an add-on that I thought was missing from Classic.

* RankWatch - Addons - World of Warcraft - CurseForge | <https://www.curseforge.com/wow/addons/rankwatch>

* Nice Work! · Issue #5 · valkyrnstudios/SpellSentinel | <https://github.com/valkyrnstudios/SpellSentinel/issues/5>

3 - The Original Files have been removed from GitHub at Tex's request.

![image](https://user-images.githubusercontent.com/55365231/147158803-e50bd77b-56fb-42b9-a94c-e73f5166cba5.png)

Also Relevant!

* Love Is Something (The Magic Penny) - YouTube || https://www.youtube.com/watch?v=4zqvcmsxCcI

**Comment by SabreValkyrn** [comment]
Thanks for this! #6?

I tried to cover history, credits, and legality in #6. Would you mind reviewing and commenting on it for posterity?

**Comment by SabreValkyrn** [comment]
Worked with @Gogo1951 via Discord to rebuild ability tables and discuss his roadmap ambitions for passing the torch.
